import { AccentColorConfig, AccentColorId, WallpaperId, AppMetadata } from '../types';

export const ACCENT_COLORS: Record<AccentColorId, AccentColorConfig> = {
  'violet-classic': {
    id: 'violet-classic',
    name: 'Obsidian Violett',
    primary: '#a855f7',
    secondary: '#7e22ce',
    glow: 'rgba(168, 85, 247, 0.3)',
    border: 'rgba(168, 85, 247, 0.45)',
    text: '#c084fc',
    bgLight: 'rgba(168, 85, 247, 0.15)',
  },
  'emerald-matrix': {
    id: 'emerald-matrix',
    name: 'Cyber Smaragdgrün',
    primary: '#10b981',
    secondary: '#047857',
    glow: 'rgba(16, 185, 129, 0.3)',
    border: 'rgba(16, 185, 129, 0.45)',
    text: '#34d399',
    bgLight: 'rgba(16, 185, 129, 0.15)',
  },
  'ocean-cyan': {
    id: 'ocean-cyan',
    name: 'Ozean Türkis',
    primary: '#06b6d4',
    secondary: '#0e7490',
    glow: 'rgba(6, 182, 212, 0.3)',
    border: 'rgba(6, 182, 212, 0.45)',
    text: '#22d3ee',
    bgLight: 'rgba(6, 182, 212, 0.15)',
  },
  'electric-blue': {
    id: 'electric-blue',
    name: 'Elektrisches Azurblau',
    primary: '#3b82f6',
    secondary: '#1d4ed8',
    glow: 'rgba(59, 130, 246, 0.3)',
    border: 'rgba(59, 130, 246, 0.45)',
    text: '#60a5fa',
    bgLight: 'rgba(59, 130, 246, 0.15)',
  },
  'sunset-amber': {
    id: 'sunset-amber',
    name: 'Sonnenuntergang Bernstein',
    primary: '#f59e0b',
    secondary: '#b45309',
    glow: 'rgba(245, 158, 11, 0.3)',
    border: 'rgba(245, 158, 11, 0.45)',
    text: '#fbbf24',
    bgLight: 'rgba(245, 158, 11, 0.15)',
  },
  'crimson-ruby': {
    id: 'crimson-ruby',
    name: 'Rubinrot Noir',
    primary: '#ef4444',
    secondary: '#b91c1c',
    glow: 'rgba(239, 68, 68, 0.3)',
    border: 'rgba(239, 68, 68, 0.45)',
    text: '#f87171',
    bgLight: 'rgba(239, 68, 68, 0.15)',
  },
  'rose-quartz': {
    id: 'rose-quartz',
    name: 'Rosa Neon',
    primary: '#ec4899',
    secondary: '#be185d',
    glow: 'rgba(236, 72, 153, 0.3)',
    border: 'rgba(236, 72, 153, 0.45)',
    text: '#f472b6',
    bgLight: 'rgba(236, 72, 153, 0.15)',
  },
  'golden-sun': {
    id: 'golden-sun',
    name: 'Solar Gold',
    primary: '#eab308',
    secondary: '#a16207',
    glow: 'rgba(234, 179, 8, 0.3)',
    border: 'rgba(234, 179, 8, 0.45)',
    text: '#fde047',
    bgLight: 'rgba(234, 179, 8, 0.15)',
  },
  'monochrome-slate': {
    id: 'monochrome-slate',
    name: 'Titanium Silber',
    primary: '#94a3b8',
    secondary: '#475569',
    glow: 'rgba(148, 163, 184, 0.25)',
    border: 'rgba(148, 163, 184, 0.4)',
    text: '#cbd5e1',
    bgLight: 'rgba(148, 163, 184, 0.12)',
  },
  'purple-amethyst': {
    id: 'purple-amethyst',
    name: 'Amethyst Kristall',
    primary: '#8b5cf6',
    secondary: '#6d28d9',
    glow: 'rgba(139, 92, 246, 0.3)',
    border: 'rgba(139, 92, 246, 0.45)',
    text: '#a78bfa',
    bgLight: 'rgba(139, 92, 246, 0.15)',
  },
  'lavender-mist': {
    id: 'lavender-mist',
    name: 'Lavendel Schein',
    primary: '#c084fc',
    secondary: '#9333ea',
    glow: 'rgba(192, 132, 252, 0.25)',
    border: 'rgba(192, 132, 252, 0.4)',
    text: '#e9d5ff',
    bgLight: 'rgba(192, 132, 252, 0.12)',
  },
  'magenta-noir': {
    id: 'magenta-noir',
    name: 'Magenta Noir',
    primary: '#d946ef',
    secondary: '#86198f',
    glow: 'rgba(217, 70, 239, 0.3)',
    border: 'rgba(217, 70, 239, 0.45)',
    text: '#f0abfc',
    bgLight: 'rgba(217, 70, 239, 0.15)',
  },
};

export const WALLPAPERS: Array<{
  id: WallpaperId;
  name: string;
  description: string;
  previewGradient: string;
}> = [
  {
    id: 'shader-obsidian',
    name: 'WebGL Obsidian Quantum (Shader)',
    description: 'Echtzeit-GLSL-Shader mit lumineszierenden Plasma-Filamenten & Mausinteraktion',
    previewGradient: 'radial-gradient(circle at center, #2e1045 0%, #11071c 50%, #08080a 100%)',
  },
  {
    id: 'shader-cyberwaves',
    name: 'WebGL Cyber Synthwave (Shader)',
    description: '3D-Horizont-Wireframe-Grid mit fließenden Neonwellen & Sternenfeld',
    previewGradient: 'radial-gradient(ellipse at bottom, #3b0764 0%, #09090b 70%)',
  },
  {
    id: 'shader-chroma',
    name: 'WebGL Chromatic Liquid (Shader)',
    description: 'Flüssige dynamische Chromagradienten mit feiner Farbverzerrung',
    previewGradient: 'linear-gradient(135deg, #1e1b4b 0%, #311042 50%, #09090b 100%)',
  },
  {
    id: 'shader-aurora',
    name: 'WebGL Quantum Aurora (Shader)',
    description: 'Wogende Polarlichter im tiefen Raum mit dynamischem Glühen',
    previewGradient: 'radial-gradient(circle at top, #064e3b 0%, #111827 60%, #030712 100%)',
  },
  {
    id: 'shader-matrix',
    name: 'WebGL Digital Matrix (Shader)',
    description: 'GPU-beschleunigter digitaler Datenregen in Tiefdunkelgrün & Violett',
    previewGradient: 'linear-gradient(180deg, #022c22 0%, #050508 70%)',
  },
  {
    id: 'shader-quantum',
    name: 'WebGL Dark Vortex (Shader)',
    description: 'Kosmischer dunkler Gravitationswirbel mit feinen Lichtringen',
    previewGradient: 'radial-gradient(circle at center, #3b0764 0%, #0a0a0f 70%)',
  },
  {
    id: 'obsidian-deep',
    name: 'Obsidian Deep',
    description: 'Tiefschwarz mit dezentem zentriertem Violett-Aura-Schimmer',
    previewGradient: 'radial-gradient(circle at center, #1e112a 0%, #0d0d11 60%, #08080a 100%)',
  },
  {
    id: 'emerald-synth',
    name: 'Cyber Emerald',
    description: 'Futuristischer Smaragd-Matrix-Dunkelverlauf mit leuchtender Tiefe',
    previewGradient: 'radial-gradient(circle at 60% 40%, #064e3b 0%, #022c22 45%, #050b08 100%)',
  },
  {
    id: 'ocean-abyss',
    name: 'Deep Pacific',
    description: 'Tiefsee-Gradient in Nachtblau und Azur mit feinem Glühen',
    previewGradient: 'radial-gradient(circle at 40% 30%, #0c4a6e 0%, #082f49 50%, #030712 100%)',
  },
  {
    id: 'sunset-dusk',
    name: 'Cyberpunk Sunset',
    description: 'Warmes Dämmerlicht mit feinem Bernstein- und Violett-Kontrast',
    previewGradient: 'linear-gradient(145deg, #451a03 0%, #1f1024 45%, #09090b 100%)',
  },
  {
    id: 'crimson-noir',
    name: 'Crimson Velvet',
    description: 'Edles sattes Karmesinrot auf dunklem Samtcarbon',
    previewGradient: 'radial-gradient(ellipse at center, #450a0a 0%, #180505 55%, #080303 100%)',
  },
  {
    id: 'golden-aurora',
    name: 'Solar Eclipse',
    description: 'Warme goldene Korona mit tiefer kosmischer Dunkelheit',
    previewGradient: 'radial-gradient(circle at top right, #422006 0%, #1c1305 45%, #0a0a0c 100%)',
  },
  {
    id: 'violet-nebula',
    name: 'Violet Nebula',
    description: 'Sternenstaub-Nebel mit sanften violetten Schleiern',
    previewGradient: 'linear-gradient(135deg, #13091e 0%, #0d0d12 50%, #170b26 100%)',
  },
  {
    id: 'cyber-grid',
    name: 'Cyber Grid',
    description: 'Geometrisches 3D-Gitter mit subtiler Horizontlinie',
    previewGradient: 'radial-gradient(ellipse at bottom, #2b1144 0%, #0c0b10 70%)',
  },
  {
    id: 'matrix-dark',
    name: 'Dark Matrix Stream',
    description: 'Dunkler Terminal-Datenstrom mit sanfter Lumineszenz',
    previewGradient: 'linear-gradient(160deg, #09090b 0%, #150d20 70%, #0b0712 100%)',
  },
  {
    id: 'anthracite-mesh',
    name: 'Anthrazit Carbon',
    description: 'Matte metallische Textur mit puristischem Minimalismus',
    previewGradient: 'linear-gradient(180deg, #18181f 0%, #101015 60%, #0a0a0d 100%)',
  },
  {
    id: 'minimal-glow',
    name: 'Minimal Glow',
    description: 'Reines mattes Schwarz mit feiner Lichtkante oben',
    previewGradient: 'radial-gradient(circle at top, #26123a 0%, #0a0a0c 65%)',
  },
];

export const APPS_REGISTRY: AppMetadata[] = [
  {
    id: 'files',
    name: 'Dateien',
    category: 'Produktivität',
    iconName: 'Folder',
    description: 'Virtueller Dateimanager mit Texteditor, Bildbetrachter und Cloud-Sync',
    defaultWidth: 860,
    defaultHeight: 560,
    minWidth: 600,
    minHeight: 420,
    isPreinstalled: true,
  },
  {
    id: 'notes',
    name: 'Notizen',
    category: 'Produktivität',
    iconName: 'FileText',
    description: 'Markdown-Notizblock mit automatischer Firebase-Cloud-Synchronisation',
    defaultWidth: 780,
    defaultHeight: 520,
    minWidth: 540,
    minHeight: 380,
    isPreinstalled: true,
  },
  {
    id: 'gallery',
    name: 'Galerie',
    category: 'Medien',
    iconName: 'Image',
    description: 'Medienbetrachter für Bilder, Hintergrundbilder und Fotos',
    defaultWidth: 820,
    defaultHeight: 540,
    minWidth: 560,
    minHeight: 400,
    isPreinstalled: true,
  },
  {
    id: 'youtube',
    name: 'YouTube',
    category: 'Medien',
    iconName: 'Youtube',
    description: 'Offizielle YouTube-App mit 4K Video-Streaming, Live-Suche, Trending & Playlists',
    defaultWidth: 1040,
    defaultHeight: 680,
    minWidth: 720,
    minHeight: 480,
    isPreinstalled: true,
  },
  {
    id: 'music',
    name: 'Musikplayer',
    category: 'Medien',
    iconName: 'Music',
    description: 'Lofi- und Ambient-Synthesizer mit Audio-Visualisierer und Soundtracks',
    defaultWidth: 680,
    defaultHeight: 460,
    minWidth: 480,
    minHeight: 360,
    isPreinstalled: true,
  },
  {
    id: 'calculator',
    name: 'Taschenrechner',
    category: 'Dienstprogramme',
    iconName: 'Calculator',
    description: 'Minimalistischer wissenschaftlicher Rechner mit Berechnungsverlauf',
    defaultWidth: 380,
    defaultHeight: 540,
    minWidth: 320,
    minHeight: 460,
    isPreinstalled: true,
  },
  {
    id: 'browser',
    name: 'Webbrowser',
    category: 'Produktivität',
    iconName: 'Globe',
    description: 'Funktionierender Internet-Browser mit Tabs, Lesezeichen & Reader-Ansicht',
    defaultWidth: 920,
    defaultHeight: 620,
    minWidth: 680,
    minHeight: 480,
    isPreinstalled: true,
  },
  {
    id: 'terminal',
    name: 'Terminal',
    category: 'Entwicklung',
    iconName: 'Terminal',
    description: 'Obsidian CLI mit Befehlen für System, Krypto, Dateiverwaltung & Matrix',
    defaultWidth: 720,
    defaultHeight: 480,
    minWidth: 500,
    minHeight: 340,
    isPreinstalled: true,
  },
  {
    id: 'monitor',
    name: 'Aktivitätsanzeige',
    category: 'System',
    iconName: 'Activity',
    description: 'Echtzeit-Ressourcenüberwachung für RAM, CPU, Speicher und Firebase Status',
    defaultWidth: 760,
    defaultHeight: 500,
    minWidth: 520,
    minHeight: 380,
    isPreinstalled: true,
  },
  {
    id: 'appstore',
    name: 'App Store',
    category: 'Store',
    iconName: 'ShoppingBag',
    description: 'Offizieller Obsidian Marktplatz für Apps, WebGL Wallpaper, Icon-Packs & System-Themes',
    defaultWidth: 920,
    defaultHeight: 600,
    minWidth: 680,
    minHeight: 460,
    isPreinstalled: true,
  },
  {
    id: 'settings',
    name: 'Einstellungen',
    category: 'System',
    iconName: 'Settings',
    description: 'Personalisierung, Farbthemen, Benutzerprofile & Firebase-Synchronisation',
    defaultWidth: 840,
    defaultHeight: 580,
    minWidth: 640,
    minHeight: 480,
    isPreinstalled: true,
  },
  {
    id: 'retro-2048',
    name: '2048 Retro',
    category: 'Dienstprogramme',
    iconName: 'Gamepad2',
    description: 'Klassisches 2048-Puzzlespiel mit Tastatursteuerung und Bestenliste',
    defaultWidth: 440,
    defaultHeight: 560,
    minWidth: 360,
    minHeight: 480,
    isPreinstalled: false,
  },
  {
    id: 'snake',
    name: 'Neon Cyber Snake',
    category: 'Dienstprogramme',
    iconName: 'Zap',
    description: 'Retro Cyberpunk Snake mit Power-Ups, Geschwindigkeitsstufen und Firebase-Bestenliste',
    defaultWidth: 640,
    defaultHeight: 580,
    minWidth: 460,
    minHeight: 440,
    isPreinstalled: false,
  },
  {
    id: 'minesweeper',
    name: 'Matrix Minensucher',
    category: 'Dienstprogramme',
    iconName: 'Bomb',
    description: 'Taktischer Minesweeper mit 3 Schwierigkeitsgraden, Flaggenmodus und Timer-Highscores',
    defaultWidth: 640,
    defaultHeight: 560,
    minWidth: 460,
    minHeight: 420,
    isPreinstalled: false,
  },
  {
    id: 'flappy-cube',
    name: 'Flappy Obsidian',
    category: 'Dienstprogramme',
    iconName: 'Rocket',
    description: 'Arkadespiel mit Neon-Laser-Hindernissen, Jump-Physik und Online-Rangliste',
    defaultWidth: 620,
    defaultHeight: 540,
    minWidth: 440,
    minHeight: 420,
    isPreinstalled: false,
  },
  {
    id: 'space-invaders',
    name: 'Galaxy Raider',
    category: 'Dienstprogramme',
    iconName: 'Crosshair',
    description: 'Retro Arcade Shoot \'em Up mit Alien-Wellen, Schutzschilden und Bonus-UFOs',
    defaultWidth: 680,
    defaultHeight: 560,
    minWidth: 480,
    minHeight: 440,
    isPreinstalled: false,
  },
  {
    id: 'cyber-memory',
    name: 'Matrix Hack Memory',
    category: 'Dienstprogramme',
    iconName: 'Brain',
    description: 'Gedächtnistraining mit Cyberpunk-Symbolen, Combo-Multiplikatoren und Zeitwertung',
    defaultWidth: 660,
    defaultHeight: 540,
    minWidth: 460,
    minHeight: 420,
    isPreinstalled: false,
  },
  {
    id: 'sudoku',
    name: 'Cyber Sudoku Master',
    category: 'Dienstprogramme',
    iconName: 'Grid3X3',
    description: 'Taktisches Zahlenrätsel mit 4 Schwierigkeitsgraden, Notizmodus, Hinweisen und Firebase-Rangliste',
    defaultWidth: 700,
    defaultHeight: 620,
    minWidth: 500,
    minHeight: 480,
    isPreinstalled: false,
  },
  {
    id: 'pomodoro',
    name: 'Pomodoro Fokus',
    category: 'Produktivität',
    iconName: 'Timer',
    description: 'Fokus-Timer mit Zyklen, Glockenalarm und integrierter Aufgabenliste',
    defaultWidth: 720,
    defaultHeight: 480,
    minWidth: 520,
    minHeight: 380,
    isPreinstalled: false,
  },
  {
    id: 'weather',
    name: 'Wetter',
    category: 'Dienstprogramme',
    iconName: 'CloudSun',
    description: 'Live-Wetterstation für europäische Metropolen mit 5-Tage-Prognose',
    defaultWidth: 680,
    defaultHeight: 520,
    minWidth: 500,
    minHeight: 400,
    isPreinstalled: false,
  },
  {
    id: 'pixel-paint',
    name: 'Pixel Paint',
    category: 'Medien',
    iconName: 'Paintbrush',
    description: 'Kreatives Zeichenstudio mit Pinseln, Farbpaletten und PNG-Export',
    defaultWidth: 820,
    defaultHeight: 580,
    minWidth: 600,
    minHeight: 440,
    isPreinstalled: false,
  },
  {
    id: 'crypto-radar',
    name: 'Krypto Radar',
    category: 'Dienstprogramme',
    iconName: 'TrendingUp',
    description: 'Echtzeit-Kurstracker mit interaktiven Trendcharts und Live-Preisen',
    defaultWidth: 780,
    defaultHeight: 520,
    minWidth: 560,
    minHeight: 400,
    isPreinstalled: false,
  },
  {
    id: 'audio-synth',
    name: 'Synthesizer',
    category: 'Medien',
    iconName: 'Music2',
    description: 'Interaktiver WebAudio-Synthesizer mit Klaviatur und Wellenformen',
    defaultWidth: 680,
    defaultHeight: 440,
    minWidth: 500,
    minHeight: 360,
    isPreinstalled: false,
  },
  {
    id: 'chess',
    name: 'Obsidian Schach',
    category: 'Spiele',
    iconName: 'Crown',
    description: 'Klassisches Schachspiel mit intelligenter KI, 2-Spieler-Modus und Analyse',
    defaultWidth: 840,
    defaultHeight: 640,
    minWidth: 620,
    minHeight: 520,
    isPreinstalled: true,
  },
];

