import React from 'react';
import {
  Settings,
  Folder,
  Calculator,
  Globe,
  Terminal,
  FileText,
  Image as ImageIcon,
  Music,
  Activity,
  ShoppingBag,
  Gamepad2,
  Timer,
  CloudSun,
  Paintbrush,
  TrendingUp,
  Music2,
  Sparkles,
  Zap,
  Code,
  Youtube,
  Crown,
  Bomb,
  Rocket,
  Brain,
  Crosshair,
  Grid3X3,
  Swords,
  Cpu,
  Compass,
  Book,
  Camera,
  Video,
  MessageSquare,
  Phone,
  Mail,
  Map,
  Heart,
  Star,
  Sun,
  Moon,
  CheckSquare,
  Search,
  Play,
  Pause,
  Volume2,
  Shield,
  Lock,
  Bell,
  Trophy,
  Award,
  Coffee,
  Gift,
  Flame,
  Feather,
  Key,
  Package,
  Layers,
  Radio,
  Tv,
  Database,
  Cloud,
  Wifi,
  Battery,
  Flag,
  HelpCircle,
  AlertTriangle,
  Bug,
  LifeBuoy,
  Bookmark,
  Calendar,
  BarChart,
  PieChart,
  LineChart,
  Sliders,
  Scissors,
  Printer,
  Paperclip,
  Eye,
  Share2,
  Download,
  Upload,
  Trash2,
  Edit3,
  Link,
  Smile,
  User,
  Users,
  Info,
  DollarSign,
  Euro,
  Percent,
  Palette,
  Clock,
  Briefcase,
  Headphones,
  Compass as CompassIcon,
  Mic,
  Speaker,
  VolumeX,
  FileCode,
  Box,
  Target,
  Dices,
  Ghost,
  ShieldCheck,
  Smartphone,
  Laptop,
  Monitor,
  Lightbulb,
} from 'lucide-react';

export const APP_ICON_MAP: Record<string, React.ComponentType<{ className?: string; style?: React.CSSProperties }>> = {
  Settings,
  Folder,
  Calculator,
  Globe,
  Terminal,
  FileText,
  Image: ImageIcon,
  ImageIcon,
  Music,
  Activity,
  ShoppingBag,
  Gamepad2,
  Timer,
  CloudSun,
  Paintbrush,
  TrendingUp,
  Music2,
  Sparkles,
  Zap,
  Code,
  Youtube,
  Crown,
  Bomb,
  Rocket,
  Brain,
  Crosshair,
  Grid3X3,
  Swords,
  Cpu,
  Compass,
  Book,
  Camera,
  Video,
  MessageSquare,
  Phone,
  Mail,
  Map,
  Heart,
  Star,
  Sun,
  Moon,
  CheckSquare,
  Search,
  Play,
  Pause,
  Volume2,
  Shield,
  Lock,
  Bell,
  Trophy,
  Award,
  Coffee,
  Gift,
  Flame,
  Feather,
  Key,
  Package,
  Layers,
  Radio,
  Tv,
  Database,
  Cloud,
  Wifi,
  Battery,
  Flag,
  HelpCircle,
  AlertTriangle,
  Bug,
  LifeBuoy,
  Bookmark,
  Calendar,
  BarChart,
  PieChart,
  LineChart,
  Sliders,
  Scissors,
  Printer,
  Paperclip,
  Eye,
  Share2,
  Download,
  Upload,
  Trash2,
  Edit3,
  Link,
  Smile,
  User,
  Users,
  Info,
  DollarSign,
  Euro,
  Percent,
  Palette,
  Clock,
  Briefcase,
  Headphones,
  Mic,
  Speaker,
  VolumeX,
  FileCode,
  Box,
  Target,
  Dices,
  Ghost,
  ShieldCheck,
  Smartphone,
  Laptop,
  Monitor,
  Lightbulb,
};

export interface IconItem {
  id: string;
  name: string;
  category: 'Spiele' | 'Medien' | 'Produktivität' | 'System' | 'Werkzeuge' | 'Symbole';
  component: React.ComponentType<{ className?: string; style?: React.CSSProperties }>;
}

export const ICON_LIBRARY_ITEMS: IconItem[] = [
  // Spiele & Gaming
  { id: 'Gamepad2', name: 'Gamepad', category: 'Spiele', component: Gamepad2 },
  { id: 'Crown', name: 'Krone', category: 'Spiele', component: Crown },
  { id: 'Bomb', name: 'Miene / Bombe', category: 'Spiele', component: Bomb },
  { id: 'Rocket', name: 'Rakete', category: 'Spiele', component: Rocket },
  { id: 'Crosshair', name: 'Fadenkreuz', category: 'Spiele', component: Crosshair },
  { id: 'Brain', name: 'Gehirn / Memory', category: 'Spiele', component: Brain },
  { id: 'Grid3X3', name: 'Raster / Sudoku', category: 'Spiele', component: Grid3X3 },
  { id: 'Swords', name: 'Schwerter', category: 'Spiele', component: Swords },
  { id: 'Target', name: 'Zielscheibe', category: 'Spiele', component: Target },
  { id: 'Dices', name: 'Würfel', category: 'Spiele', component: Dices },
  { id: 'Ghost', name: 'Geist', category: 'Spiele', component: Ghost },
  { id: 'Trophy', name: 'Trophäe', category: 'Spiele', component: Trophy },
  { id: 'Award', name: 'Medaille', category: 'Spiele', component: Award },
  { id: 'Flame', name: 'Flamme', category: 'Spiele', component: Flame },
  { id: 'Zap', name: 'Blitz', category: 'Spiele', component: Zap },

  // Medien & Unterhaltung
  { id: 'Music', name: 'Musik', category: 'Medien', component: Music },
  { id: 'Music2', name: 'Synth / Note', category: 'Medien', component: Music2 },
  { id: 'Youtube', name: 'Video Portal', category: 'Medien', component: Youtube },
  { id: 'Camera', name: 'Kamera', category: 'Medien', component: Camera },
  { id: 'Video', name: 'Film / Video', category: 'Medien', component: Video },
  { id: 'Headphones', name: 'Kopfhörer', category: 'Medien', component: Headphones },
  { id: 'Radio', name: 'Radio', category: 'Medien', component: Radio },
  { id: 'Tv', name: 'Fernseher', category: 'Medien', component: Tv },
  { id: 'Paintbrush', name: 'Pinsel', category: 'Medien', component: Paintbrush },
  { id: 'Palette', name: 'Farbpalette', category: 'Medien', component: Palette },
  { id: 'Image', name: 'Galerie', category: 'Medien', component: ImageIcon },
  { id: 'Speaker', name: 'Lautsprecher', category: 'Medien', component: Speaker },
  { id: 'Mic', name: 'Mikrofon', category: 'Medien', component: Mic },

  // Produktivität & Büro
  { id: 'FileText', name: 'Dokument', category: 'Produktivität', component: FileText },
  { id: 'Calendar', name: 'Kalender', category: 'Produktivität', component: Calendar },
  { id: 'Timer', name: 'Timer', category: 'Produktivität', component: Timer },
  { id: 'Clock', name: 'Uhrzeit', category: 'Produktivität', component: Clock },
  { id: 'CheckSquare', name: 'Aufgaben', category: 'Produktivität', component: CheckSquare },
  { id: 'Briefcase', name: 'Arbeit', category: 'Produktivität', component: Briefcase },
  { id: 'Book', name: 'Buch', category: 'Produktivität', component: Book },
  { id: 'Bookmark', name: 'Lesezeichen', category: 'Produktivität', component: Bookmark },
  { id: 'Edit3', name: 'Notizen', category: 'Produktivität', component: Edit3 },
  { id: 'Mail', name: 'E-Mail', category: 'Produktivität', component: Mail },
  { id: 'Phone', name: 'Telefon', category: 'Produktivität', component: Phone },
  { id: 'MessageSquare', name: 'Nachrichten', category: 'Produktivität', component: MessageSquare },
  { id: 'BarChart', name: 'Balkendiagramm', category: 'Produktivität', component: BarChart },
  { id: 'LineChart', name: 'Liniendiagramm', category: 'Produktivität', component: LineChart },
  { id: 'PieChart', name: 'Kreisdiagramm', category: 'Produktivität', component: PieChart },
  { id: 'TrendingUp', name: 'Krypto / Trend', category: 'Produktivität', component: TrendingUp },

  // System & Verwaltung
  { id: 'Settings', name: 'Einstellungen', category: 'System', component: Settings },
  { id: 'Folder', name: 'Dateien / Ordner', category: 'System', component: Folder },
  { id: 'Terminal', name: 'Terminal', category: 'System', component: Terminal },
  { id: 'Shield', name: 'Sicherheit', category: 'System', component: Shield },
  { id: 'ShieldCheck', name: 'Geschützt', category: 'System', component: ShieldCheck },
  { id: 'Lock', name: 'Sperren', category: 'System', component: Lock },
  { id: 'Key', name: 'Schlüssel', category: 'System', component: Key },
  { id: 'Cpu', name: 'Prozessor / CPU', category: 'System', component: Cpu },
  { id: 'Database', name: 'Datenbank', category: 'System', component: Database },
  { id: 'Wifi', name: 'WLAN', category: 'System', component: Wifi },
  { id: 'Battery', name: 'Batterie', category: 'System', component: Battery },
  { id: 'Activity', name: 'Aktivität', category: 'System', component: Activity },
  { id: 'User', name: 'Benutzer', category: 'System', component: User },
  { id: 'Users', name: 'Benutzergruppe', category: 'System', component: Users },
  { id: 'ShoppingBag', name: 'App Store', category: 'System', component: ShoppingBag },
  { id: 'Monitor', name: 'Bildschirm', category: 'System', component: Monitor },
  { id: 'Laptop', name: 'Laptop', category: 'System', component: Laptop },
  { id: 'Smartphone', name: 'Mobilgerät', category: 'System', component: Smartphone },

  // Werkzeuge & Dienstprogramme
  { id: 'Calculator', name: 'Rechner', category: 'Werkzeuge', component: Calculator },
  { id: 'Globe', name: 'Internet / Browser', category: 'Werkzeuge', component: Globe },
  { id: 'CloudSun', name: 'Wetter', category: 'Werkzeuge', component: CloudSun },
  { id: 'Code', name: 'Code Editor', category: 'Werkzeuge', component: Code },
  { id: 'FileCode', name: 'Skripte', category: 'Werkzeuge', component: FileCode },
  { id: 'Compass', name: 'Kompass', category: 'Werkzeuge', component: Compass },
  { id: 'Map', name: 'Karte', category: 'Werkzeuge', component: Map },
  { id: 'Search', name: 'Suche', category: 'Werkzeuge', component: Search },
  { id: 'Sliders', name: 'Regler', category: 'Werkzeuge', component: Sliders },
  { id: 'Package', name: 'Paket', category: 'Werkzeuge', component: Package },
  { id: 'Layers', name: 'Ebenen', category: 'Werkzeuge', component: Layers },
  { id: 'Box', name: 'Container', category: 'Werkzeuge', component: Box },
  { id: 'Download', name: 'Herunterladen', category: 'Werkzeuge', component: Download },
  { id: 'Upload', name: 'Hochladen', category: 'Werkzeuge', component: Upload },
  { id: 'Trash2', name: 'Papierkorb', category: 'Werkzeuge', component: Trash2 },
  { id: 'Printer', name: 'Drucker', category: 'Werkzeuge', component: Printer },

  // Symbole & Markierungen
  { id: 'Sparkles', name: 'Funken / KI', category: 'Symbole', component: Sparkles },
  { id: 'Star', name: 'Stern', category: 'Symbole', component: Star },
  { id: 'Heart', name: 'Herz', category: 'Symbole', component: Heart },
  { id: 'Sun', name: 'Sonne', category: 'Symbole', component: Sun },
  { id: 'Moon', name: 'Mond', category: 'Symbole', component: Moon },
  { id: 'Lightbulb', name: 'Idee / Glühbirne', category: 'Symbole', component: Lightbulb },
  { id: 'Coffee', name: 'Kaffee', category: 'Symbole', component: Coffee },
  { id: 'Gift', name: 'Geschenk', category: 'Symbole', component: Gift },
  { id: 'Feather', name: 'Feder', category: 'Symbole', component: Feather },
  { id: 'Smile', name: 'Lächeln', category: 'Symbole', component: Smile },
  { id: 'Bell', name: 'Glocke', category: 'Symbole', component: Bell },
  { id: 'Flag', name: 'Flagge', category: 'Symbole', component: Flag },
  { id: 'HelpCircle', name: 'Hilfe', category: 'Symbole', component: HelpCircle },
  { id: 'AlertTriangle', name: 'Warnung', category: 'Symbole', component: AlertTriangle },
  { id: 'DollarSign', name: 'Dollar', category: 'Symbole', component: DollarSign },
  { id: 'Euro', name: 'Euro', category: 'Symbole', component: Euro },
];

export const ALL_APP_ICON_NAMES: string[] = ICON_LIBRARY_ITEMS.map((item) => item.id);

export interface AppIconProps {
  name: string;
  className?: string;
  style?: React.CSSProperties;
  fallback?: React.ReactNode;
}

export const AppIcon: React.FC<AppIconProps> = ({ name, className = 'w-5 h-5', style, fallback }) => {
  // Direct match or normalized lookup
  const Component = APP_ICON_MAP[name] || APP_ICON_MAP[name.charAt(0).toUpperCase() + name.slice(1)];

  if (Component) {
    return <Component className={className} style={style} />;
  }

  if (fallback) {
    return <>{fallback}</>;
  }

  // Generic stylish fallback
  return <Sparkles className={className} style={style} />;
};
